### ISSUE TITLE
SIGHASH_ALL added twice

### ISSUE THREAD

**Issue by mrx23dot** [BlockIo/block_io-python#26]
Hi,
When signing a p2pkh I think your lib adds **SIGHASH_ALL** redundantly since it's already added by btc util lib:

```
secretkey.sign_input()
    sighash=SIGHASH_ALL
    signature += struct.pack('B', sighash)
```

your's
```
signature_with_sighash(signature, sighash = constants.SIGHASH_ALL)
return hexlify(unhexlify(signature) + (sighash).to_bytes(1, byteorder="big"))
```

thus creating 193vbyte length instead of 192 vBytes
How come this passed test cases and never caused problem?

**Comment by doersf** [comment]
This is addressed here: https://github.com/BlockIo/block_io-python/blob/master/block_io/bitcoinutils_patches.py#L58

**Comment by doersf** [comment]
As for serialized tx size, if it's coming from the signature, the difference would be the low R signatures. This implementation fixes signature size, but it's possible in some cases to get lower sized signatures.

**Comment by doersf** [comment]
The address's specifics are unknown until the address reveals its script: that happens when it spends an output. The signature script/witness reveals the distinction, the specifics are a bit involved.
