### ISSUE TITLE
Uncompressed P2PKH fails

### ISSUE THREAD

**Issue by mrx23dot** [BlockIo/block_io-python#27]
Hi,
I tried to spend from uncompressed P2PKH (don't laugh :)
but I think the generated signature is invalid for that.

`get_address()` has default parameter `compressed=True` thus generating invalid h160 into scriptsig.

```
elif cur_address_type == 'P2PKH' or cur_address_type == 'P2WPKH-over-P2SH' or cur_address_type == 'P2WPKH':
    pkh_script = get_output_script(PublicKey(cur_public_keys[0]).get_address().to_string())
```

It should select compressed parameter based on first byte of provided pubkey '02'/'04' to compressed=True/False

Just a note, bytes and strings are mixed in the lib.

**Comment by doersf** [comment]
Use of uncompressed pubkeys isn't something we're going to support. You will want to build your own transactions using uncompressed pubkeys and broadcast them through directly or through an API like chain.so/api.
