### ISSUE TITLE
setup.py should declare abstract dependencies only (no versions)

### ISSUE THREAD

**Issue by miohtama** [BlockIo/block_io-python#9]
setup.py now declares version pindowns for its dependencies. This is not the best practice - it makes it troublematic to deploy block.io library with your application if your application happens to use other minor version of these packages. 

setup.py should declare versionless dependencies only. For the reference, and for the CI testing, one can supply referential `requirements.txt` which known good set of absolute versions of dependencies. Then you can mix block.io `requirements.txt` with your application `requirements.txt`.

Further read about the topic:

https://caremad.io/2013/07/setup-vs-requirement/

**Comment by doersf** [comment]
Agreed. Library updated to 1.1.4.
